### ISSUE TITLE
I'd to use this again.

### ISSUE THREAD

**Issue by PlumpMath** [chr15m/blender-hylang-live-code#8]
It doesn't work because it's upgraded to Blender 2.8 and Hy 0.17.
I want to use this again.
Help me. Thanks~*.

**Comment by chr15m** [comment]
Hello. What is the error that you see? What happens vs what you expect to happen?

**Comment by PlumpMath** [comment]
.../blender-hylang-live-code/entry-py-watcher.py", line 41, in execute
    self._timer = wm.event_timer_add(0.1, context.window)
TypeError: WindowManager.event_timer_add(): required parameter "window" to be a keyword argument!

------------------------------------------------------------------------
sorry without explain error.
. :) 
and.. 
With the upgrade hy 0.17, the module import function (hy) seems to have changed slightly.

When I import the module, it didn't respond.
Especially, I do not know how to import from the changed file.
I think there's an error there.

Thanks.

**Comment by chr15m** [comment]
@PlumpMath I am not sure how soon I'll be able to fix this - in the mean time you could try installing an older version of Hy in a virtualenv. Will certainly accept a PR upgrading the code to a newer version of Hy. Unfortunately Hy is a language that makes breaking changes between versions making it hard to maintain.

**Comment by PlumpMath** [comment]
Unfortunately Hy is a language that makes breaking changes between versions making it hard to maintain.
<--- I agree. 

Thank you for your reply in my question.
I'm fine even if the work is delayed.
Thank you very very much for making this module.
:) Good day

**Comment by darwin** [comment]
FYI, I got it working again here: https://github.com/darwin/blender-hylang-live-code

**Comment by chr15m** [comment]
:clap: king! :crown:

PR?

**Comment by darwin** [comment]
It is still a work in progress, but if you like the changes, feel free to merge them back.

I'd like to continue and get nREPL working and then ideally use it from Cursive IDE. This will probably involve some trickery to make hy look like clj to make Cursive happy about it. So I will be probably doing a lot of changes which might not be what you want in your repo.

**Comment by chr15m** [comment]
Cool, I will give it a test and maybe @PlumpMath will have time to check out your fork too. If it works ok I'll merge it back.

The nREPL stuff sounds neat. If you can get it behind some kind of a flag so it's optional then I will certainly merge all of it, but if it's extra work don't worry. Godspeed!

**Comment by PlumpMath** [comment]
I was interested in using the Blender Python module for libpython-clj these
days. We've actually done it.
But I haven't checked.
 Session maintenance seemed to be a little bit problematic with the bpy
module.

2020년 2월 27일 (목) 오후 10:39, Chris McCormick <notifications@github.com>님이 작성:

**Comment by darwin** [comment]
I also looked in to libpython-clj but rejected it because that would limit my interaction with Blender into what is allowed background mode only. 

I'm a Blender noob but this sounded like a big limitation - https://youtu.be/8rJkm9MKyg8?t=653

**Comment by sutyrin** [comment]
@chr15m please review this small fix. 

Thanks hugely for pointing out to 
1) Hy language
2) Live coding setup at Blender. 

These two could be of great fun!
